# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network requests to Segment, Inc. to collect metrics on Podfile execution.
# To disable this behavior, add `ENV['COCOAPODS_DISABLE_STATS'] = 'true'` to your Podfile.
#
# For more information, see https://guides.cocoapods.org/syntax/podfile.html#podfile.

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get has been run first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require_relative File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_plugins(self)
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end 